const fakeData = [
    {
        id: 1,
        img:"https://i.ibb.co/dKQfbCH/snap195.png",
        title:"Modern JavaScript From The Beginning with project",
        instructor:"Brad Traversy",
        rating:"8.9/10",
        price:150,
    },
    {
        id: 2,
        img:"https://i.ibb.co/G5zq50f/1-Na-Um-Bti42n0-FMMffyj-Tt-Bg.jpg",
        title:"Web Design for Beginners: Coding in HTML & CSS",
        instructor:"Brad Schiff",
        rating:"8/10",
        price:220,
    },
    {
        id: 3,
        img:"https://i.ibb.co/bs4NkPp/bootstrap.png",
        title:"Learn Bootstrap By Building Projects - Includes Bootstrap 5",
        instructor:"Eduonix Learning Solutions",
        rating:"7.5/10",
        price:120,
    },
    {
        id: 4,
        img:"https://i.ibb.co/7vZGPNR/px-Python.png",
        title:"Python for Absolute Beginners",
        instructor:"Rehatpal Singh",
        rating:"6.3/10",
        price:200,
    },
    {
        id: 5,
        img:"https://i.ibb.co/G9HfJP2/How-to-Learn-Python.jpg",
        title:"Python Mega Course: Build Applications",
        instructor:"Tarra C",
        rating:"6/10",
        price:205,
    },
    {
        id: 6,
        img:"https://i.ibb.co/cCKpB1y/php.png",
        title:"PHP for Absolute Beginners",
        instructor:"John Callahan",
        rating:"8/10",
        price:270,
    },
    {
        id: 7,
        img:"https://i.ibb.co/nsx5TQs/bootstrap-wordpress-responsive.png",
        title:"WordPress Theme Development with Bootstrap",
        instructor:"Amanda Hankerson",
        rating:"5/10",
        price:160,
    },
    {
        id: 8,
        img:"https://i.ibb.co/vmSVF8L/git.png",
        title:"Git Complete: The definitive, step-by-step guide to Git",
        instructor:"Jared Noynay",
        rating:"6/10",
        price:70,
    },
    {
        id: 9,
        img:"https://i.ibb.co/ZSgr47s/apple-ios-app.jpg",
        title:"Learn and Understand Building Modern iOS Apps [2020]",
        instructor:"Precious Ndukauba",
        rating:"9.9/10",
        price:95,
    },
    {
        id: 10,
        img:"https://i.ibb.co/KhZRfvM/2400-1260-rw-blog-node-js.png",
        title:"The Complete Node.js Developer Course [2020]",
        instructor:"Saksham",
        rating:"5.9/10",
        price:60,
    },
    {
        id: 11,
        img:"https://i.ibb.co/3TpdsnL/Custom-Software-Development.jpg",
        title:"Software Development-OOP, UML, Agile and more",
        instructor:"Mohak Arora",
        rating:"5/10",
        price:180,
    },
    {
        id: 12,
        img:"https://i.ibb.co/4KZfbHp/php-opp-ajex.jpg",
        title:"Building Database Web App PHP | OOP | AJAX | MySQL",
        instructor:"Sam",
        rating:"7.9/10",
        price:140,
    },
    {
        id: 13,
        img:"https://i.ibb.co/NnRhymh/html5-and-css3.png",
        title:"Build Responsive Website using HTML5 and CSS3",
        instructor:"Pratik Patel",
        rating:"6.7/10",
        price:64,
    },
    {
        id: 14,
        img:"https://i.ibb.co/bbKTHww/ps.jpg",
        title:"Ultimate Photoshop Training: From Beginner to Pro",
        instructor:"Keino Campbell, Esq.",
        rating:"7.4/10",
        price:230,
    },
    {
        id: 15,
        img:"https://i.ibb.co/bXM76qX/software-architecture.jpg",
        title:"Software Architecture for the Enterprise Architect",
        instructor:"Farhat Ahmad",
        rating:"6/10",
        price:135,
    },
    {
        id: 16,
        img:"https://i.ibb.co/JtGdJYR/video-editing.jpg",
        title:"Premiere Pro CC for Beginners: Video Editing in Premiere",
        instructor:"Vaibhav Singh Rajput",
        rating:"9/10",
        price:90,
    },
    {
        id: 17,
        img:"https://i.ibb.co/9Nn5wRh/java-binary-code-gears-programming-coding-development-by-bluebay2014-gettyimages-1040871468-2400x160.jpg",
        title:"Java Programming Masterclass for Software Developers",
        instructor:"Tim Buchalka",
        rating:"7/10",
        price:190,
    },
    {
        id: 18,
        img:"https://i.ibb.co/2ysR0fH/art-art-history-main-1440x800.jpg",
        title:"Character Art School: Complete Character Drawing Course",
        instructor:"Goran Lochert",
        rating:"7.2/10",
        price:50,
    },
]

export default fakeData;